name: Linux Build

on: [push]

jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        sudo apt install -y liblapack-dev
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j
    
    - name: CTest
      run: ctest
