name: Linux Build

on: [push]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build and Run
      run: |
        mkdir build
        cd build
        cmake .. -DCMAKE_BUILD_TYPE=Release
        make -j
    
    - name: CTest
      run: ctest
