name: Windows Build

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: |
        cmake -G "Visual Studio 17 2022"
        cmake --build build
    
    - name: CTest
      run: |
        cd unit-test
        ctest
      
