name: Windows Build

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build and run
      run: |
        cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -Sc:/ -Bc:/build -G "Visual Studio 17 2022"
    
    - name: ctest
      run: |
        ls
        cd build
        ctest
      
