name: Windows Build

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: build and run
      run: |
        cmake --no-warn-unused-cli -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE -G "Visual Studio 17 2022"
        cmake --build .
    
    - name: ctest
      run: |
        cd unit-test
        ctest
      
